In [4]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("pandas/Euro_2012_stats_TEAM.csv")

In [4]:
data.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [5]:
data.columns = data.columns.str.lower().str.replace(" ","_")

In [6]:
data.groupby("team")["goals"].sum().sort_values(ascending = False).head(1)

team
Spain    12
Name: goals, dtype: int64

In [7]:
data.groupby("team")["total_shots_(inc._blocked)"].sum().sort_values(ascending = False).head(1)

team
Italy    110
Name: total_shots_(inc._blocked), dtype: int64

In [8]:
data[data["team"] == "Italy"]

,team,goals,shots_on_target,shots_off_target,shooting_accuracy,%_goals-to-shots,total_shots_(inc._blocked),hit_woodwork,penalty_goals,penalties_not_scored,...,saves_made,saves-to-shots_ratio,fouls_won,fouls_conceded,offsides,yellow_cards,red_cards,subs_on,subs_off,players_used
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19

In [9]:
data.groupby("team")["yellow_cards"].sum().idxmax()

'Italy'

In [10]:
data.head()

,team,goals,shots_on_target,shots_off_target,shooting_accuracy,%_goals-to-shots,total_shots_(inc._blocked),hit_woodwork,penalty_goals,penalties_not_scored,...,saves_made,saves-to-shots_ratio,fouls_won,fouls_conceded,offsides,yellow_cards,red_cards,subs_on,subs_off,players_used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [11]:
data.groupby("team")["shooting_accuracy"].sum().sort_values(ascending = False).head(3)

team
Spain      55.9%
Croatia    51.9%
Denmark    50.0%
Name: shooting_accuracy, dtype: object

In [12]:
data.team.sort_values(by = "shooting_accuracy", ascending = False)

TypeError: Series.sort_values() got an unexpected keyword argument 'by'

In [13]:
data.sort_values(by = "goals",ascending = False)[["team","goals"]].head()

        team  goals
13     Spain     12
5    Germany     10
10  Portugal      6
7      Italy      6
14    Sweden      5

In [14]:
data["shooting_accuracy"] = data["shooting_accuracy"].str.replace("%","")

In [15]:
avg = data["shooting_accuracy"].astype(float).mean();avg

np.float64(39.71875)

In [16]:
data["shooting_accuracy"] = data["shooting_accuracy"].astype(float)

In [17]:
data[data["shooting_accuracy"] > avg][["team", "shooting_accuracy"]]

              team  shooting_accuracy
0          Croatia               51.9
1   Czech Republic               41.9
2          Denmark               50.0
3          England               50.0
5          Germany               47.8
7            Italy               43.0
13           Spain               55.9
14          Sweden               47.2

In [18]:
data.head()

,team,goals,shots_on_target,shots_off_target,shooting_accuracy,%_goals-to-shots,total_shots_(inc._blocked),hit_woodwork,penalty_goals,penalties_not_scored,...,saves_made,saves-to-shots_ratio,fouls_won,fouls_conceded,offsides,yellow_cards,red_cards,subs_on,subs_off,players_used
0,Croatia,4,13,12,51.9,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [22]:
data_fouls = data[["team","goals","yellow_cards","fouls_conceded"]];data_fouls.head()

             team  goals  yellow_cards  fouls_conceded
0         Croatia      4             9              62
1  Czech Republic      4             7              73
2         Denmark      4             4              38
3         England      5             5              45
4          France      3             6              51

Hem sarı kartı 10’dan fazla olan hem de faul sayısı 100’den fazla olan takımlar hangileridir?

In [30]:
data_fouls.query("yellow_cards > 10 and fouls_conceded > 50")

        team  goals  yellow_cards  fouls_conceded
7      Italy      6            16              89
10  Portugal      6            12              90
13     Spain     12            11              83

In [26]:
data_fouls[data_fouls["yellow_cards"] > 10]

        team  goals  yellow_cards  fouls_conceded
7      Italy      6            16              89
10  Portugal      6            12              90
13     Spain     12            11              83

In [28]:
data_fouls[data_fouls["fouls_conceded"] > 50]

                   team  goals  yellow_cards  fouls_conceded
0               Croatia      4             9              62
1        Czech Republic      4             7              73
4                France      3             6              51
7                 Italy      6            16              89
9                Poland      2             7              56
10             Portugal      6            12              90
11  Republic of Ireland      1             6              51
13                Spain     12            11              83
14               Sweden      5             7              51

In [33]:
data_fouls[
            (data_fouls["yellow_cards"] > 10) & 
            (data_fouls["fouls_conceded"] > 50)
            ]

        team  goals  yellow_cards  fouls_conceded
7      Italy      6            16              89
10  Portugal      6            12              90
13     Spain     12            11              83

In [52]:
data[["team","yellow_cards"]].sort_values(by = "yellow_cards",ascending = False).head()

        team  yellow_cards
7      Italy            16
10  Portugal            12
13     Spain            11
0    Croatia             9
6     Greece             9

In [55]:
data.sort_values(by = "shooting_accuracy",ascending = False)[["team","shooting_accuracy"]].head(1)

     team  shooting_accuracy
13  Spain               55.9

In [46]:
#Find the teams that have lowest and highest number of yellow cards. 
#Note that more than one country can have the same maximum number or minimum number of yellow cards.

Problem 1.
Euro 2012 stats TEAM.csv file contains statistics of the teams that attended Europen Cup 2012. Using this data do the following tasks: 
a) Find the teams that have lowest and highest number of yellow cards. Note that more than one country can have the same maximum number or minimum number of yellow cards. 
b) Find the team that has the best shooting accuracy.

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     object
 5   % Goals-to-shots            16 non-null     object
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     object
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     object
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

In [5]:
data.Team

0                 Croatia
1          Czech Republic
2                 Denmark
3                 England
4                  France
5                 Germany
6                  Greece
7                   Italy
8             Netherlands
9                  Poland
10               Portugal
11    Republic of Ireland
12                 Russia
13                  Spain
14                 Sweden
15                Ukraine
Name: Team, dtype: object

In [6]:
data["Yellow Cards"].sort_values(ascending = False).head()

7     16
10    12
13    11
0      9
6      9
Name: Yellow Cards, dtype: int64

In [7]:
data.sort_values(by = "Yellow Cards", ascending = False)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15

In [8]:
data.sort_values(by = "Yellow Cards", ascending = False)[["Team","Yellow Cards"]].head() #Italy have the max number of yellow card

        Team  Yellow Cards
7      Italy            16
10  Portugal            12
13     Spain            11
0    Croatia             9
6     Greece             9

In [9]:
data.sort_values(by = "Yellow Cards")[["Team","Yellow Cards"]].head()  #Denmark and Germany have the min number of yellow card

           Team  Yellow Cards
2       Denmark             4
5       Germany             4
3       England             5
8   Netherlands             5
15      Ukraine             5

In [1]:
data.head()

NameError: name 'data' is not defined

section b - Find the team that has the best shooting accuracy.

In [10]:
data.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [11]:
data["Shooting Accuracy"]

0     51.9%
1     41.9%
2     50.0%
3     50.0%
4     37.9%
5     47.8%
6     30.7%
7     43.0%
8     25.0%
9     39.4%
10    34.3%
11    36.8%
12    22.5%
13    55.9%
14    47.2%
15    21.2%
Name: Shooting Accuracy, dtype: object

In [12]:
data.sort_values(by = ("Shooting Accuracy"),ascending = False)[["Team", "Shooting Accuracy"]].head(3)

       Team Shooting Accuracy
13    Spain             55.9%
0   Croatia             51.9%
2   Denmark             50.0%

In [13]:
data.sort_values(by = ("Shooting Accuracy"),ascending = False)[["Team", "Shooting Accuracy"]].iloc[0]

Team                 Spain
Shooting Accuracy    55.9%
Name: 13, dtype: object

In [14]:
print("The team that has the highest scoring accuracy: {}".format(data.sort_values(by="Shooting Accuracy", ascending=False)["Team"].iloc[0]))

The team that has the highest scoring accuracy: Spain

In [15]:
data.columns = data.columns.str.lower().str.replace(" ","_")

In [16]:
data.head()

,team,goals,shots_on_target,shots_off_target,shooting_accuracy,%_goals-to-shots,total_shots_(inc._blocked),hit_woodwork,penalty_goals,penalties_not_scored,...,saves_made,saves-to-shots_ratio,fouls_won,fouls_conceded,offsides,yellow_cards,red_cards,subs_on,subs_off,players_used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [19]:
data.columns

Index(['team', 'goals', 'shots_on_target', 'shots_off_target',
       'shooting_accuracy', '%_goals-to-shots', 'total_shots_(inc._blocked)',
       'hit_woodwork', 'penalty_goals', 'penalties_not_scored', 'headed_goals',
       'passes', 'passes_completed', 'passing_accuracy', 'touches', 'crosses',
       'dribbles', 'corners_taken', 'tackles', 'clearances', 'interceptions',
       'clearances_off_line', 'clean_sheets', 'blocks', 'goals_conceded',
       'saves_made', 'saves-to-shots_ratio', 'fouls_won', 'fouls_conceded',
       'offsides', 'yellow_cards', 'red_cards', 'subs_on', 'subs_off',
       'players_used'],
      dtype='object')

In [23]:
data = data.drop(['shots_on_target', 'shots_off_target',
       'shooting_accuracy', '%_goals-to-shots', 'total_shots_(inc._blocked)','passes', 'passes_completed', 'passing_accuracy', 'touches', 'crosses',
       'dribbles', 'corners_taken', 'tackles', 'clearances', 'interceptions',
       'clearances_off_line', 'clean_sheets', 'blocks', 'goals_conceded',
       'saves_made', 'saves-to-shots_ratio', 'fouls_won', 'fouls_conceded',
       'offsides'])

KeyError: "['shots_on_target', 'shots_off_target', 'shooting_accuracy', '%_goals-to-shots', 'total_shots_(inc._blocked)', 'passes', 'passes_completed', 'passing_accuracy', 'touches', 'crosses', 'dribbles', 'corners_taken', 'tackles', 'clearances', 'interceptions', 'clearances_off_line', 'clean_sheets', 'blocks', 'goals_conceded', 'saves_made', 'saves-to-shots_ratio', 'fouls_won', 'fouls_conceded', 'offsides'] not found in axis"

In [27]:
data2 = data[['team', 'goals', 'shots_on_target','shooting_accuracy', '%_goals-to-shots']];data2

,team,goals,shots_on_target,shooting_accuracy,%_goals-to-shots
0,Croatia,4,13,51.9%,16.0%
1,Czech Republic,4,13,41.9%,12.9%
2,Denmark,4,10,50.0%,20.0%
3,England,5,11,50.0%,17.2%
4,France,3,22,37.9%,6.5%
5,Germany,10,32,47.8%,15.6%
6,Greece,5,8,30.7%,19.2%
7,Italy,6,34,43.0%,7.5%
8,Netherlands,2,12,25.0%,4.1%
9,Poland,2,15,39.4%,5.2%
10,Portugal,6,22,34.3%,9.3%
11,Republic of Ireland,1,7,36.8%,5.2%
12,Russia,5,9,22.5%,12.5%
13,Spain,12,42,55.9%,16.0%
14,Sweden,5,17,47.2%,13.8%
15,Ukraine,2,7,21.2%,6.0%

In [32]:
data2.sort_values(by = "goals",ascending = False).head()

        team  goals  shots_on_target shooting_accuracy %_goals-to-shots
13     Spain     12               42             55.9%            16.0%
5    Germany     10               32             47.8%            15.6%
10  Portugal      6               22             34.3%             9.3%
7      Italy      6               34             43.0%             7.5%
14    Sweden      5               17             47.2%            13.8%

The csv file AutoSurvey.csv contains a sample of data about vehicles owned, whether they were purchased new or used, and other types of data. The data file looks like the figure below.
a- Print average mileage for each car type. Average of mileages should be grouped into columns  as New and Used, as shown below 
b- For each car type find the difference between maximum and minimum Vehichle Age

In [5]:
auto = pd.read_csv("AutoSurvey.csv")

In [6]:
auto.head()

   Gender       Type Purchased  Vehicle_Age  Mileage   MPG
0    Male   Mid-size      Used         15.0   127233  28.7
1  Female   Mid-size       New          1.0    23970  43.4
2    Male      Small       New          7.0    77392  24.0
3  Female  Large SUV      Used         14.0   185397  15.2
4  Female      Small       New          2.0    26001  37.0

In [7]:
#Hem new olan
#Hem de mpg ortalamanın ÜSTÜNDE olan

In [8]:
auto.columns = auto.columns.str.lower().str.replace(" ","")

In [9]:
len(auto)

23

In [10]:
mpg_mean = auto["mpg"].mean();mpg_mean

np.float64(29.078260869565216)

In [11]:
auto[auto["mpg"] > mpg_mean]

    gender      type purchased  vehicle_age  mileage   mpg
1   Female  Mid-size       New          1.0    23970  43.4
4   Female     Small       New          2.0    26001  37.0
6     Male     Small      Used          6.0    72083  45.7
7     Male     Small       New         11.0   165353  42.0
8     Male     Small      Used         13.0   205288  33.0
9   Female     Small       New          7.0   142897  31.0
15  Female     Small      Used         10.0   105628  35.0
16  Female     Small       New          5.0    48678  30.4
17    Male  Mid-size       New          0.5     6849  40.2
18  Female     Small      Used         10.0   137941  30.0
21  Female     Small      Used         12.0   134172  31.0

In [12]:
auto[auto["purchased"] == "New"]
auto.query("mpg > mpg_mean and purchased == 'New'")

UndefinedVariableError: name 'mpg_mean' is not defined

In [ ]:
auto[
(auto["purchased"] == "New") &
(auto["mpg"] > mpg_mean) 
].sort_values(by = "mpg",ascending = False)

In [ ]:
auto.head()

In [ ]:
#En yüksek ortalama mpg'ye sahip
#araç modeli hangisidir ve bu ortalama kaçtır?

In [ ]:
auto.mpg.sort_values(ascending = False).idxmax()

In [ ]:
auto.iloc[6]

In [29]:
auto["mileage_per_year"] = auto["mileage"] / auto["vehicle_age"];auto.head()
auto["mileage_per_year"].round()

0      8482.0
1     23970.0
2     11056.0
3     13243.0
4     13000.0
5     20071.0
6     12014.0
7     15032.0
8     15791.0
9     20414.0
10    13042.0
11    10806.0
12    11057.0
13    13816.0
14    18701.0
15    10563.0
16     9736.0
17    13698.0
18    13794.0
19     7456.0
20     6126.0
21    11181.0
22     7199.0
Name: mileage_per_year, dtype: float64

In [30]:
auto.head()

   gender       type purchased  vehicle_age  mileage   mpg  mileage_per_year
0    Male   Mid-size      Used         15.0   127233  28.7       8482.200000
1  Female   Mid-size       New          1.0    23970  43.4      23970.000000
2    Male      Small       New          7.0    77392  24.0      11056.000000
3  Female  Large SUV      Used         14.0   185397  15.2      13242.642857
4  Female      Small       New          2.0    26001  37.0      13000.500000

In [ ]:
auto.pivot_table(index = "type", columns = "purchased", values = "mpg")

Type bazında tek bir tablo üret ve şu metrikler olsun:

araç sayısı (satır sayısı)

ortalama MPG

maksimum MPG

Vehicle_Age farkı: max(Vehicle_Age) - min(Vehicle_Age)

ortalama Mileage_per_Year

In [31]:
auto.groupby("type").agg(
    vehicle_count = ("type","size"),
    avg_mpg = ("mpg","mean"),
    max_mpg = ("mpg","max"),
    vehicle_age_diff = ("vehicle_age", lambda x:x.max() - x.min()),
    avg_mileage_py = ("mileage_per_year", "mean"))

           vehicle_count    avg_mpg  max_mpg  vehicle_age_diff  avg_mileage_py
type
Large SUV              2  18.100000     21.0              7.00    15971.678571
Mid-size               5  33.520000     43.4             14.75    13433.023333
Minivan                2  16.000000     20.0              5.00    16556.579365
Small                 11  33.372727     45.7             11.00    13058.015091
Small SUV              3  21.966667     24.9             10.00     8129.251832

E) Kazananı Bul (sort + idxmax)
“En verimli araç tipi”ni şu skorla tanımla:
Efficiency_Score = MPG / Mileage_per_Year
Her satır için bu skoru hesapla.
Sonra Type bazında ortalama Efficiency_Score hesapla.
En yüksek ortalama skora sahip Type hangisi? (idxmax)
Bu Type’ın skor değeri kaç? (max)

In [39]:
auto["efficiency_score"] = auto.mpg / auto.mileage_per_year

In [41]:
auto.head()

,gender,type,purchased,vehicle_age,mileage,mpg,mileage_per_year,efficiency_score
0,Male,Mid-size,Used,15.0,127233,28.7,8482.200000,0.003384
1,Female,Mid-size,New,1.0,23970,43.4,23970.000000,0.001811
2,Male,Small,New,7.0,77392,24.0,11056.000000,0.002171
3,Female,Large SUV,Used,14.0,185397,15.2,13242.642857,0.001148
4,Female,Small,New,2.0,26001,37.0,13000.500000,0.002846

In [60]:
auto.groupby("type")["efficiency_score"].mean().round(4)

type
Large SUV    0.0011
Mid-size     0.0028
Minivan      0.0010
Small        0.0026
Small SUV    0.0029
Name: efficiency_score, dtype: float64

In [61]:
auto.groupby("type")["efficiency_score"].mean().idxmax()

'Small SUV'

In [63]:
auto.groupby("type")["efficiency_score"].mean().max()

0.002872855473486769

In [13]:
auto.query("mpg > @mpg_mean and purchased == 'New'")

    gender      type purchased  vehicle_age  mileage   mpg
1   Female  Mid-size       New          1.0    23970  43.4
4   Female     Small       New          2.0    26001  37.0
7     Male     Small       New         11.0   165353  42.0
9   Female     Small       New          7.0   142897  31.0
16  Female     Small       New          5.0    48678  30.4
17    Male  Mid-size       New          0.5     6849  40.2

Purchased == "New" ama Vehicle_Age >= 5 olanlar

Purchased == "Used" ama Vehicle_Age <= 1 olanlar

In [64]:
auto.head()

,gender,type,purchased,vehicle_age,mileage,mpg,mileage_per_year,efficiency_score
0,Male,Mid-size,Used,15.0,127233,28.7,8482.200000,0.003384
1,Female,Mid-size,New,1.0,23970,43.4,23970.000000,0.001811
2,Male,Small,New,7.0,77392,24.0,11056.000000,0.002171
3,Female,Large SUV,Used,14.0,185397,15.2,13242.642857,0.001148
4,Female,Small,New,2.0,26001,37.0,13000.500000,0.002846

In [73]:
auto.query("purchased == 'New' and vehicle_age >= 5")

,gender,type,purchased,vehicle_age,mileage,mpg,mileage_per_year,efficiency_score
2,Male,Small,New,7.0,77392,24.0,11056.000000,0.002171
5,Female,Minivan,New,9.0,180643,20.0,20071.444444,0.000996
7,Male,Small,New,11.0,165353,42.0,15032.090909,0.002794
9,Female,Small,New,7.0,142897,31.0,20413.857143,0.001519
14,Female,Large SUV,New,7.0,130905,21.0,18700.714286,0.001123
16,Female,Small,New,5.0,48678,30.4,9735.600000,0.003123

In [75]:
auto.query("purchased == 'Used' and vehicle_age <= 2")

Empty DataFrame
Columns: [gender, type, purchased, vehicle_age, mileage, mpg, mileage_per_year, efficiency_score]
Index: []

In [14]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   gender       23 non-null     object
 1   type         23 non-null     object
 2   purchased    23 non-null     object
 3   vehicle_age  23 non-null     float64
 4   mileage      23 non-null     int64
 5   mpg          23 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.2+ KB

In [15]:
len(auto)

23

In [16]:
auto.Type = auto.Type.str.replace(" ","")

AttributeError: 'DataFrame' object has no attribute 'Type'

In [17]:
auto.head()

   gender       type purchased  vehicle_age  mileage   mpg
0    Male   Mid-size      Used         15.0   127233  28.7
1  Female   Mid-size       New          1.0    23970  43.4
2    Male      Small       New          7.0    77392  24.0
3  Female  Large SUV      Used         14.0   185397  15.2
4  Female      Small       New          2.0    26001  37.0

In [18]:
auto.groupby(["Type"],as_index=False)[["Mileage"]].mean()

KeyError: 'Type'

In [ ]:
auto.pivot_table(values = "Mileage", index = "Type", columns = "Purchased", aggfunc="mean")

In [ ]:
#For each car type find the difference between maximum and minimum Vehichle Age 
a = auto.Vehicle_Age.max() - auto["Vehicle_Age"].min()

In [ ]:
a

In [ ]:
auto.groupby("Type")["Vehicle_Age"].agg(lambda x:x.max() - x.min()).to_frame()

In [19]:
#Print average mileage for each car type. Average of mileages should be grouped into columns as New and Used, as shown below 
auto.head(3)

   gender      type purchased  vehicle_age  mileage   mpg
0    Male  Mid-size      Used         15.0   127233  28.7
1  Female  Mid-size       New          1.0    23970  43.4
2    Male     Small       New          7.0    77392  24.0

In [20]:
auto.pivot_table(values = "Mileage", index = "Type", columns = "Purchased",aggfunc="mean")

KeyError: 'Mileage'

In [ ]:
bread = pd.read_csv("BreadBasket_DMS.csv");bread.head()

In [108]:
bread.columns = bread.columns.str.lower().str.replace(" ","")

In [114]:
bread.item.unique()

array(['Bread', 'Scandinavian', 'Hot chocolate', 'Jam', 'Cookies',
       'Muffin', 'Coffee', 'Pastry', 'Medialuna', 'Tea', 'NONE',
       'Tartine', 'Basket', 'Mineral water', 'Farm House', 'Fudge',
       'Juice', "Ella's Kitchen Pouches", 'Victorian Sponge', 'Frittata',
       'Hearty & Seasonal', 'Soup', 'Pick and Mix Bowls', 'Smoothies',
       'Cake', 'Mighty Protein', 'Chicken sand', 'Coke',
       'My-5 Fruit Shoot', 'Focaccia', 'Sandwich', 'Alfajores', 'Eggs',
       'Brownie', 'Dulce de Leche', 'Honey', 'The BART', 'Granola',
       'Fairy Doors', 'Empanadas', 'Keeping It Local', 'Art Tray',
       'Bowl Nic Pitt', 'Bread Pudding', 'Adjustment', 'Truffles',
       'Chimichurri Oil', 'Bacon', 'Spread', 'Kids biscuit', 'Siblings',
       'Caramel bites', 'Jammie Dodgers', 'Tiffin', 'Olum & polenta',
       'Polenta', 'The Nomad', 'Hack the stack', 'Bakewell',
       'Lemon and coconut', 'Toast', 'Scone', 'Crepes', 'Vegan mincepie',
       'Bare Popcorn', 'Muesli', 'Crisps', 'Pintxos', 'Gingerbread syrup',
       'Panatone', 'Brioche and salami', 'Afternoon with the baker',
       'Salad', 'Chicken Stew', 'Spanish Brunch',
       'Raspberry shortbread sandwich', 'Extra Salami or Feta',
       'Duck egg', 'Baguette', "Valentine's card", 'Tshirt',
       'Vegan Feast', 'Postcard', 'Nomad bag', 'Chocolates',
       'Coffee granules ', 'Drinking chocolate spoons ',
       'Christmas common', 'Argentina Night', 'Half slice Monster ',
       'Gift voucher', 'Cherry me Dried fruit', 'Mortimer', 'Raw bars',
       'Tacos/Fajita'], dtype=object)

In [116]:
bread.item.str.lower().str.replace(" ","")

0               bread
1        scandinavian
2        scandinavian
3        hotchocolate
4                 jam
             ...
21288          coffee
21289             tea
21290          coffee
21291          pastry
21292       smoothies
Name: item, Length: 21293, dtype: object

In [127]:
bread.groupby("item")["transaction"].count().sort_values(ascending = False).head(10)

item
Coffee           5471
Bread            3325
Tea              1435
Cake             1025
Pastry            856
NONE              786
Sandwich          771
Medialuna         616
Hot chocolate     590
Cookies           540
Name: transaction, dtype: int64

In [121]:
bread.item.value_counts().head

item
Coffee           5471
Bread            3325
Tea              1435
Cake             1025
Pastry            856
NONE              786
Sandwich          771
Medialuna         616
Hot chocolate     590
Cookies           540
Name: count, dtype: int64

In [123]:
bread.groupby("item").size().sort_values(ascending=False).head(10)

item
Coffee           5471
Bread            3325
Tea              1435
Cake             1025
Pastry            856
NONE              786
Sandwich          771
Medialuna         616
Hot chocolate     590
Cookies           540
dtype: int64

In [142]:
a = bread[bread.item == "Coffee"]["transaction"].nunique()

4528

In [145]:
bread.groupby("item").sum().sort_values(by= "item").head(5)

,date,time,transaction
item,,,
Adjustment,2016-11-09,19:49:22,938
Afternoon with the baker,2017-01-062017-01-072017-01-082017-01-112017-0...,14:17:5913:19:0715:28:3414:15:3714:51:5618:15:...,286028
Alfajores,2016-11-012016-11-012016-11-012016-11-012016-1...,13:11:3413:41:5315:02:2316:07:1109:18:5310:53:...,1512575
Argentina Night,2017-03-112017-03-232017-04-022017-04-082017-0...,15:38:2013:44:4913:52:5408:58:1908:59:0010:43:...,64153
Art Tray,2016-11-082016-11-082016-11-102016-11-102016-1...,12:23:1112:33:1711:32:0716:21:0513:32:2613:01:...,140877